apiVersion: v1
kind: Secret
metadata:
  name: dcwf-secret
type: Opaque
stringData:
  # Remplace cette valeur par une clé secrète générée aléatoirement
  # Tu peux générer une clé avec: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
  DJANGO_SECRET_KEY: "django-insecure-63+s%a^vtne=0rbb$l@k9_vw61lf*0!tk%y6gu(hqw%q6llz%i"
---
